version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379/12"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379/12"
    command: bundle exec sidekiq
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}

  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data

volumes:
  db_data:
  bundler_gems:
  redis: